### ISSUE TITLE
Question about direct-property-access

### ISSUE THREAD

**Issue by sheriffderek** [DockYard/eslint-plugin-ember-suave#33]
Hello. I'm checking out the latest incarnation of suave. I just added it to a 2.8 LTS project and was surprised to see it throwing errors on files like `app.js`. Question 1: is the code presented below the preferred way to address this in app.js? Question 2: Will the 2.9 CLI blueprints have `Ember` destructured like that by default or will every new project have ~13 errors to start out with. Question 3: is this purely visual to keep things looking "clean" or are there performance / or future tree shaking type things building this thought? I'm trying to decide whether to turn that rule off. I'm teaching people Ember, and explicitly seeing what methods are `Ember.something()` has been integral. I can see how the destructuring could also be useful for clearly choosing what you'll use, but I want to avoid abstracting things any further depending on the answers to these questions.

Also, I would suggest including in your rule examples, something like the app.js to be specific about at least one blueprint.

https://github.com/DockYard/eslint-plugin-ember-suave/blob/master/docs/rules/no-direct-property-access.md

```
import Ember from 'ember';
import Resolver from './resolver';
import loadInitializers from 'ember-load-initializers';
import config from './config/environment';

const { Application } = Ember;

let App;

Ember.MODEL_FACTORY_INJECTIONS = true;

App = Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver
});

loadInitializers(App, config.modulePrefix);

export default App;

```

OR in the router, for example:

```
import Ember from 'ember';
import config from './config/environment';

const { Router } = Ember;

// This feels a little weird!
const myRouter = Router.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

myRouter.map(function() {
  // ......
});

export default myRouter;
```

Thank you!

**Comment by brzpegasus** [comment]
> Question 1: is the code presented below the preferred way to address this in app.js?

Yes, it is the preferred way. However, take "preferred" with a grain of salt, as the style rule set is highly opinionated. It has been an emerging pattern though, and you are likely to find more and more [examples](https://github.com/emberjs/data/blob/88f7dba3a3e957d1d9c3e930f5fea6cf37301afc/tests/dummy/app/helpers/reopen-instrumentation.js#L5-L11) that use destructuring.

> Question 2: Will the 2.9 CLI blueprints have Ember destructured like that by default or will every new project have ~13 errors to start out with.

It has been suggested to the Ember CLI team to update the blueprints and use destructuring. However, the team felt doing so would create more churn than desired, especially since the structure will change further once the ES6 module syntax is finalized. You can check out the discussion [here](https://github.com/ember-cli/ember-cli/pull/6114).

> Question 3: is this purely visual to keep things looking "clean" or are there performance / or future tree shaking type things building this thought?

The primary reason for introducing destructuring in the first place is that the path forward will be to access `Application`, `get`, `set`, and other properties currently attached to `Ember` from module imports, e.g. `import Application from 'ember/application'`. When that lands, the changes needed will be isolated to simply removing the `const` destructuring block at the top of the file and adjusting the imports (hopefully that is something that can be automated). I believe there are also performance benefits associated with using destructuring as opposed to direct property access, especially when the latter occurs over and over.

**Comment by sheriffderek** [comment]
Thank you very much for that thorough explanation.
