### ISSUE TITLE
Why no-direct-property-access on Ember and DS?

### ISSUE THREAD

**Issue by kennyadsl** [DockYard/eslint-plugin-ember-suave#40]
Hi there, I'm relatively new to Ember and ES2015/ES6 and I'm trying to understand ember-suave rules. Right now I cannot find any explanation about [no-direct-property-access](https://github.com/DockYard/eslint-plugin-ember-suave/blob/master/docs/rules/no-direct-property-access.md):

> The preferred way of accessing properties of Ember or DS is to destructure them off of the main variable, as opposed to accessing the property directly.

Can you please briefly explain why or point me to some resource that explains it?

**Comment by alexlafroscia** [comment]
I think generally, the idea is that this:

```js
import Ember from 'ember';

const { isEmpty } = Ember;

if (isEmpty(foo)) {
  ...
}
```

is preferable to this:

```js
import Ember from 'ember';

if (Ember.isEmpty(foo)) {
  ...
}
```

because in the near future, the proper way to access these utilities would be to import them directly:

```js
import { isEmpty } from '@ember/utils';

if (isEmpty(foo)) {
  ...
}
```

So destructuring them off of the global now makes the upgrade path here a little easily. You can read a bit more about the new module API that has been agreed upon [here](https://github.com/tomdale/rfcs/blob/76e03092a74c306347fa87bd7079f14cba24f7b6/text/0000-javascript-module-api.md).

Additionally, breaking things off of the global makes your code a bit cleaner, since the `Ember` prefix to `isEmpty` isn't really necessary to repeat in your code.

**Comment by brzpegasus** [comment]
There's an active PR in our styleguides that provides more explanation regarding this rule: https://github.com/DockYard/styleguides/pull/107/files

**Comment by kennyadsl** [comment]
Thanks, it's clear now! What about linking [that page](https://github.com/DockYard/styleguides/blob/1f25f3892a3f92fa42fde9e491d91021d871fcd1/engineering/ember.md) on the [rule description](https://github.com/DockYard/eslint-plugin-ember-suave/blob/master/docs/rules/no-direct-property-access.md) once the PR is merged?
