### ISSUE TITLE
error  Strings must use singlequote  quotes for backquote

### ISSUE THREAD

**Issue by jackmatt2** [DockYard/eslint-plugin-ember-suave#42]
I am getting `error  Strings must use singlequote  quotes` because I am using ES6 backquote for templated strings.  Can this be allowed by default?  Either single quote or backquote?

**Comment by rwjblue** [comment]
I don't fully follow what you are saying. Can you share a snippet that flags as "bad" and what it needs as a correction?

**Comment by jackmatt2** [comment]
Example

```
{
  title: `Hello World`
}
```

**Comment by jackmatt2** [comment]
it looks like it is only happening when no template variables are passed.  I guess that might be reasonable then.

**Comment by brzpegasus** [comment]
@jackmatt2 Yes, that is correct. You will get that error if you use back ticks for regular strings (not template strings). This is because the default config for strings is to use [single quotes](https://github.com/DockYard/eslint-plugin-ember-suave/blob/d63cc580f2ca687a56bd5c9a596e10005932a489/config/base.js#L40).

I'm going to close this as a non-issue.
